version: "2"

formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports

  settings:
    gci:
      sections:
        - standard
        - default
        - prefix(github.com/joshdk/modfmt)

linters:
  default: all

  disable:
    # Linters that are not used for this project.
    - depguard
    - err113
    - exhaustruct
    - forbidigo
    - gochecknoglobals
    - gosec
    - mnd
    - noinlineerr
    - varnamelen
    - wrapcheck

    # Linters that are deprecated.
    - wsl

  settings:
    errcheck:
      exclude-functions:
        - fmt.Fprint
        - fmt.Fprintf
        - fmt.Fprintln

    gomoddirectives:
      replace-local: true

    goheader:
      template: |-
        Copyright Josh Komoroske. All rights reserved.
        Use of this source code is governed by the MIT license,
        a copy of which can be found in the LICENSE.txt file.
        SPDX-License-Identifier: MIT
