version: 2

builds:
  - goos:
      - darwin
      - linux

    goarch:
      - amd64
      - arm64

    flags:
      - -buildvcs=false
      - -trimpath

    ldflags:
      - -buildid=
      - -s
      - -w

    env:
      - CGO_ENABLED=0
