version: 2

builds:
  - goos:
      - darwin
      - linux

    goarch:
      - amd64
      - arm64

    flags:
      - -buildvcs=false
      - -trimpath

    ldflags:
      - -X github.com/joshdk/modfmt/cmd.revision={{ .FullCommit }}
      - -X github.com/joshdk/modfmt/cmd.timestamp={{ .Date }}
      - -X github.com/joshdk/modfmt/cmd.version={{ .Summary }}
      - -buildid=
      - -s
      - -w

    env:
      - CGO_ENABLED=0
