name: build

on:
  pull_request:
  push:
    branches:
      - "master"

jobs:
  modules:
    name: modules
    runs-on: ubuntu-latest

    permissions:
      contents: read

    outputs:
      paths: ${{ steps.find-modules.outputs.paths }}

    steps:
      - uses: actions/checkout@v5

      - id: find-modules
        shell: sh
        run: echo "paths=$(find . -name go.mod | xargs dirname | jq -cnR '[inputs]')" >> $GITHUB_OUTPUT

  test:
    name: test
    runs-on: ubuntu-latest
    needs: modules

    permissions:
      contents: read

    strategy:
      fail-fast: false
      matrix:
        paths: ${{ fromJSON(needs.modules.outputs.paths) }}

    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - shell: sh
        run: |-
          cd ${{ matrix.paths }}
          go test -v ./...

  build:
    name: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - uses: goreleaser/goreleaser-action@v6
        with:
          # https://github.com/goreleaser/goreleaser/releases/tag/v2.12.7
          version: v2.12.7
          args: build --clean --snapshot

      - shell: sh
        run: ./dist/modfmt_linux_amd64_v1/modfmt --version

      - shell: sh
        run: ./dist/modfmt_linux_amd64_v1/modfmt -c -l ./...

      - uses: actions/upload-artifact@v4
        continue-on-error: true
        with:
          name: artifacts
          path: dist/
          retention-days: 1
