name: lint

on:
  pull_request:

jobs:
  lint:
    name: commitlint
    runs-on: ubuntu-latest

    permissions:
      contents: read
      pull-requests: read

    steps:
      - uses: actions/checkout@v5

      - uses: wagoid/commitlint-github-action@v6
